# Tässä tiedostossa ovat koko sivuston asetukset.

# Sivuston pääotsikko
title: Martin koulun vanhis

# Sähköpostiosoite
email: martinkarkkisade@gmail.com

# Sivuston kuvaus
description: >- # this means to ignore newlines until "header_pages:"
  Martin koulun vanhempainyhdistys ry toimii Luostarivuoren koulun Martin
  yksikön yhteydessä Turussa.

# Tässä lueteltu ylävalikkoon tulevat sivut järjestyksessä
header_pages:
    - yhdistyksestä.md
    - toiminta.md
    - johtokunta.md
    - säännöt.md
    - materiaalit.md

# Automaattisesti koostettavat sivut
collections:
    johtokunta:    # Johtokunta-sivu
        output: true






# Teknisemmät jutut

# Sivuston osoitteen alku, jos tarvitaan.
baseurl: "" # the subpath of your site, e.g. /blog
# Sivuston osoite, jos tarvitaan.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Twitter-tunnus, jos joskus hankitaan.
#twitter_username: jekyllrb
# Github-käyttäjänimi
github_username:  Martinvanhis

# Käytettävän teeman nimi
theme: minima

# Teeman asetuksia
minima:
    date_format: "%d.%m.%Y"  # Päiväyksen muoto: suomalainen

# Muita käytettäviä lisäosia
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
